development:
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
test:
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
production:
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>